- name: install apt packages
  apt: name="{{ item }}" state=present update_cache=yes
  with_items:
    - build_essential
    - git
  when:
    - apt_packages is defined
    - ansible_pkg_mgr == "apt"
